trigger:
  branches:
    include:
      - master
      - refs/tags/*
pr:
  autoCancel: true
  branches:
    include:
      - master

resources:
  repositories:
    - repository: rsg
      type: github
      name: RocketSurgeonsGuild/AzureDevopsTemplates
      ref: refs/tags/v0.7.9
      endpoint: github

variables:
  - group: rsg-bot
  - name: CONFIGURATION
    value: Release
  - name: VERBOSITY
    value: Normal
  - name: COVERAGE
    value: "$(Agent.BuildDirectory)/c"
  - name: ARTIFACTS
    value: $(Build.ArtifactStagingDirectory)
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: "true"
  - name: CodeCovToken
    value: '80df2feb-d5a2-47a7-94c7-58950d489d4c'

jobs:
  - template: pipeline/nuke.yml@rsg
    parameters:
      Configuration: $(Configuration)
      Verbosity: $(Verbosity)
      GitHub: true
      GitHubPackages: false
      DotNetVersion: "2.2.300"
      DotNet3Version: "3.0.100-preview6-012264"
      NuGetVersion: "5.1.0"
